// Auto-generated from IMPORTANT LISTE COMPLÈTE DES SPOTS (1).txt
// Generated on 2025-10-25T08:50:40.619Z
// Total spots: 250

import { PaddleSpot } from './types';

export const quebecSpots: PaddleSpot[] = [
  {
    "id": "spot-0001",
    "name": "Camping Pontmain",
    "latitude": 46.7167,
    "longitude": -75.4833,
    "description": "Type: Terrain de camping | Note: 4.6 (23)",
    "address": "Pontmain, QC",
    "photoURL": "https://www.quebecvacances.com/images/attrait/large/100/100_2951.jpg",
    "type": "Terrain de camping",
    "rating": 4.6
  },
  {
    "id": "spot-0002",
    "name": "Parc Jack Layton",
    "latitude": 45.3173,
    "longitude": -74.0648,
    "description": "Type: Parc | Note: 4.6 (506)",
    "address": "Hudson, QC",
    "photoURL": "https://www.hudson.quebec/wp-content/uploads/2021/06/JackLaytonPark.jpg",
    "type": "Parc",
    "rating": 4.6
  },
  {
    "id": "spot-0003",
    "name": "Lac Provost - Plage",
    "latitude": 46.315,
    "longitude": -74.499,
    "description": "Type: Terrain de camping | Note: 4.7 (195) | Notes: Ce lieu n'existe plus",
    "address": "695 Chem. de la Gabelle, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/parc-national-du-mont-tremblant/plage-provost.jpg",
    "type": "Terrain de camping",
    "rating": 4.7
  },
  {
    "id": "spot-0004",
    "name": "Débarcadère municipal du Lac Maskinongé",
    "latitude": 46.2167,
    "longitude": -73.05,
    "description": "Type: Rampe de mise à l'eau | Note: 3.5 (8)",
    "address": "Maskinongé, QC",
    "photoURL": "https://www.maskinonge.ca/wp-content/uploads/2020/06/debarcadere.jpg",
    "type": "Rampe de mise à l'eau",
    "rating": 3.5
  },
  {
    "id": "spot-0005",
    "name": "AGIR Maskinongé",
    "latitude": 46.2167,
    "longitude": -73.05,
    "description": "Type: Expert-conseil en environnement | Note: 4.0 (1)",
    "address": "Maskinongé, QC",
    "photoURL": "https://agir-maskinonge.org/wp-content/uploads/2021/03/logo-agir-maskinonge.jpg",
    "type": "Expert-conseil en environnement",
    "rating": 4
  },
  {
    "id": "spot-0006",
    "name": "Lac McGregor",
    "latitude": 45.6333,
    "longitude": -75.7167,
    "description": "Type: Lac | Note: 4.7 (35)",
    "address": "Val-des-Monts, QC",
    "photoURL": "https://www.val-des-monts.net/wp-content/uploads/2020/07/lac-mcgregor.jpg",
    "type": "Lac",
    "rating": 4.7
  },
  {
    "id": "spot-0007",
    "name": "Parc le Trou de la Fée",
    "latitude": 48.5833,
    "longitude": -71.25,
    "description": "Type: Attraction touristique | Note: 4.4 (1332) | Notes: Km 25",
    "address": "103 Chem. de la Vallée, Stoneham-et-Tewkesbury, QC G3C 2H8",
    "photoURL": "https://www.troudelafee.com/images/parc-trou-de-la-fee.jpg",
    "type": "Attraction touristique",
    "rating": 4.4
  },
  {
    "id": "spot-0008",
    "name": "Parc Antoine-Gauthier",
    "latitude": 46.8167,
    "longitude": -71.2167,
    "description": "Type: Parc | Note: 4.6 (448)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/lieux/parc-antoine-gauthier.jpg",
    "type": "Parc",
    "rating": 4.6
  },
  {
    "id": "spot-0009",
    "name": "Sepaq. Lac au Sorcier",
    "latitude": 47,
    "longitude": -72,
    "description": "Type: Terrain de camping | Note: 4.4 (14)",
    "address": "Réserve faunique Mastigouche, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/mastigouche/lac-au-sorcier.jpg",
    "type": "Terrain de camping",
    "rating": 4.4
  },
  {
    "id": "spot-0010",
    "name": "Lac Normand",
    "latitude": 47,
    "longitude": -72,
    "description": "Type: Lac | Note: 5.0 (3)",
    "address": "Réserve faunique Mastigouche, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/mastigouche/lac-normand.jpg",
    "type": "Lac",
    "rating": 5
  },
  {
    "id": "spot-0011",
    "name": "Plage municipale de Saint-Donat",
    "latitude": 46.3167,
    "longitude": -74.2167,
    "description": "Type: Plage | Note: 4.5 (210)",
    "address": "Saint-Donat, QC",
    "photoURL": "https://www.saint-donat.ca/wp-content/uploads/2020/06/plage-municipale.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0012",
    "name": "Parc régional de la Rivière Gentilly",
    "latitude": 46.3667,
    "longitude": -72.2167,
    "description": "Type: Parc régional | Note: 4.7 (342)",
    "address": "Bécancour, QC",
    "photoURL": "https://www.rivieregentilly.com/wp-content/uploads/2021/05/parc-riviere-gentilly.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0013",
    "name": "Lac Simon",
    "latitude": 46,
    "longitude": -75,
    "description": "Type: Lac | Note: 4.6 (112)",
    "address": "Duhamel, QC",
    "photoURL": "https://www.duhamel.ca/wp-content/uploads/2020/07/lac-simon.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0014",
    "name": "Plage du Lac des Sables",
    "latitude": 46.3167,
    "longitude": -74.2167,
    "description": "Type: Plage | Note: 4.4 (89)",
    "address": "Sainte-Agathe-des-Monts, QC",
    "photoURL": "https://www.sainte-agathe.org/images/plage-lac-des-sables.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0015",
    "name": "Parc de la Yamaska",
    "latitude": 45.4167,
    "longitude": -72.8667,
    "description": "Type: Parc national | Note: 4.6 (1023)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/yamaska/parc-yamaska.jpg",
    "type": "Parc national",
    "rating": 4.6
  },
  {
    "id": "spot-0016",
    "name": "Plage municipale de Saint-Faustin",
    "latitude": 46.1,
    "longitude": -74.5,
    "description": "Type: Plage | Note: 4.3 (67)",
    "address": "Saint-Faustin-Lac-Carré, QC",
    "photoURL": "https://www.saint-faustin.ca/images/plage-municipale.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0017",
    "name": "Lac Taureau",
    "latitude": 46.7,
    "longitude": -73.8,
    "description": "Type: Réservoir | Note: 4.8 (512)",
    "address": "Saint-Michel-des-Saints, QC",
    "photoURL": "https://www.saint-michel.ca/images/lac-taureau.jpg",
    "type": "Réservoir",
    "rating": 4.8
  },
  {
    "id": "spot-0018",
    "name": "Plage municipale de Saint-Zénon",
    "latitude": 46.5,
    "longitude": -73.7,
    "description": "Type: Plage | Note: 4.2 (34)",
    "address": "Saint-Zénon, QC",
    "photoURL": "https://www.saint-zenon.ca/images/plage-municipale.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0019",
    "name": "Parc régional des Grandes-Rivières",
    "latitude": 46.9,
    "longitude": -72,
    "description": "Type: Parc régional | Note: 4.5 (198)",
    "address": "Shawinigan, QC",
    "photoURL": "https://www.shawinigan.ca/images/parc-grandes-rivieres.jpg",
    "type": "Parc régional",
    "rating": 4.5
  },
  {
    "id": "spot-0020",
    "name": "Plage municipale de Saint-Gabriel",
    "latitude": 46.3,
    "longitude": -73.3,
    "description": "Type: Plage | Note: 4.6 (145)",
    "address": "Saint-Gabriel, QC",
    "photoURL": "https://www.saint-gabriel.ca/images/plage-municipale.jpg",
    "type": "Plage",
    "rating": 4.6
  },
  {
    "id": "spot-0021",
    "name": "Plage municipale de Saint-Ferréol-les-Neiges",
    "latitude": 47.1,
    "longitude": -70.8833,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Saint-Ferréol-les-Neiges, QC",
    "photoURL": "https://www.stferreollesneiges.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0022",
    "name": "Parc du Mont-Orford",
    "latitude": 45.3333,
    "longitude": -72.2167,
    "description": "Type: Parc national | Note: 4.7 (1456)",
    "address": "Orford, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/orford/parc-mont-orford.jpg",
    "type": "Parc national",
    "rating": 4.7
  },
  {
    "id": "spot-0023",
    "name": "Plage municipale de Saint-Aimé-des-Lacs",
    "latitude": 47.75,
    "longitude": -70.2167,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Aimé-des-Lacs, QC",
    "photoURL": "https://www.st-aime-des-lacs.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0024",
    "name": "Lac Saint-Joseph",
    "latitude": 46.8833,
    "longitude": -71.5,
    "description": "Type: Lac | Note: 4.6 (98)",
    "address": "Fossambault-sur-le-Lac, QC",
    "photoURL": "https://www.fossambault-sur-le-lac.com/images/lac-saint-joseph.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0025",
    "name": "Plage municipale de Sainte-Anne-de-Sorel",
    "latitude": 46.05,
    "longitude": -73.0167,
    "description": "Type: Plage | Note: 4.3 (41)",
    "address": "Sainte-Anne-de-Sorel, QC",
    "photoURL": "https://www.sainteannedesorel.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0026",
    "name": "Parc régional du Poisson Blanc",
    "latitude": 46.25,
    "longitude": -75.5,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Notre-Dame-du-Laus, QC",
    "photoURL": "https://www.poissonblanc.ca/images/parc-poisson-blanc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0027",
    "name": "Plage municipale de Saint-Mathieu-du-Parc",
    "latitude": 46.6,
    "longitude": -72.9,
    "description": "Type: Plage | Note: 4.2 (29)",
    "address": "Saint-Mathieu-du-Parc, QC",
    "photoURL": "https://www.stmathieuduparc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0028",
    "name": "Lac des Îles",
    "latitude": 47,
    "longitude": -73,
    "description": "Type: Lac | Note: 4.5 (64)",
    "address": "Saint-Michel-des-Saints, QC",
    "photoURL": "https://www.saint-michel.ca/images/lac-des-iles.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0029",
    "name": "Plage municipale de Saint-Alphonse-Rodriguez",
    "latitude": 46.25,
    "longitude": -73.5,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Saint-Alphonse-Rodriguez, QC",
    "photoURL": "https://www.st-alphonse-rodriguez.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0030",
    "name": "Parc régional de la Forêt Ouareau",
    "latitude": 46.3167,
    "longitude": -73.6,
    "description": "Type: Parc régional | Note: 4.6 (312)",
    "address": "Notre-Dame-de-la-Merci, QC",
    "photoURL": "https://www.parcsregionaux.org/images/ouareau.jpg",
    "type": "Parc régional",
    "rating": 4.6
  },
  {
    "id": "spot-0031",
    "name": "Plage municipale de Saint-Calixte",
    "latitude": 45.95,
    "longitude": -73.85,
    "description": "Type: Plage | Note: 4.3 (47)",
    "address": "Saint-Calixte, QC",
    "photoURL": "https://www.saint-calixte.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0032",
    "name": "Lac des Pins",
    "latitude": 46,
    "longitude": -73.9,
    "description": "Type: Lac | Note: 4.6 (59)",
    "address": "Saint-Calixte, QC",
    "photoURL": "https://www.saint-calixte.ca/images/lac-des-pins.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0033",
    "name": "Plage municipale de Saint-Côme",
    "latitude": 46.3333,
    "longitude": -73.6,
    "description": "Type: Plage | Note: 4.5 (88)",
    "address": "Saint-Côme, QC",
    "photoURL": "https://www.saint-come.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0034",
    "name": "Parc régional du Lac Taureau",
    "latitude": 46.7,
    "longitude": -73.8,
    "description": "Type: Parc régional | Note: 4.7 (412)",
    "address": "Saint-Michel-des-Saints, QC",
    "photoURL": "https://www.parcsregionaux.org/images/lac-taureau.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0035",
    "name": "Plage municipale de Saint-Jean-de-Matha",
    "latitude": 46.25,
    "longitude": -73.5,
    "description": "Type: Plage | Note: 4.4 (62)",
    "address": "Saint-Jean-de-Matha, QC",
    "photoURL": "https://www.saintjeandematha.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0036",
    "name": "Lac Vert",
    "latitude": 46.4,
    "longitude": -73.7,
    "description": "Type: Lac | Note: 4.5 (38)",
    "address": "Saint-Damien, QC",
    "photoURL": "https://www.saint-damien.ca/images/lac-vert.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0037",
    "name": "Plage municipale de Saint-Damien",
    "latitude": 46.4,
    "longitude": -73.7,
    "description": "Type: Plage | Note: 4.3 (51)",
    "address": "Saint-Damien, QC",
    "photoURL": "https://www.saint-damien.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0038",
    "name": "Parc régional des Chutes Monte-à-Peine-et-des-Dalles",
    "latitude": 46.25,
    "longitude": -73.5,
    "description": "Type: Parc régional | Note: 4.8 (723)",
    "address": "Sainte-Mélanie, QC",
    "photoURL": "https://www.parcsregionaux.org/images/chutes-monte-a-peine.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0039",
    "name": "Plage municipale de Sainte-Mélanie",
    "latitude": 46.25,
    "longitude": -73.5,
    "description": "Type: Plage | Note: 4.2 (33)",
    "address": "Sainte-Mélanie, QC",
    "photoURL": "https://www.sainte-melanie.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0040",
    "name": "Lac Maskinongé",
    "latitude": 46.2167,
    "longitude": -73.05,
    "description": "Type: Lac | Note: 4.6 (74)",
    "address": "Maskinongé, QC",
    "photoURL": "https://www.maskinonge.ca/images/lac-maskinonge.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0041",
    "name": "Plage municipale de Louiseville",
    "latitude": 46.25,
    "longitude": -72.95,
    "description": "Type: Plage | Note: 4.3 (56)",
    "address": "Louiseville, QC",
    "photoURL": "https://www.louiseville.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0042",
    "name": "Parc des Chutes de Sainte-Ursule",
    "latitude": 46.3667,
    "longitude": -73,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Sainte-Ursule, QC",
    "photoURL": "https://www.sainte-ursule.ca/images/chutes.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0043",
    "name": "Plage municipale de Yamachiche",
    "latitude": 46.25,
    "longitude": -72.9,
    "description": "Type: Plage | Note: 4.2 (44)",
    "address": "Yamachiche, QC",
    "photoURL": "https://www.yamachiche.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0044",
    "name": "Lac Saint-Pierre",
    "latitude": 46.2,
    "longitude": -72.8,
    "description": "Type: Réserve de biosphère | Note: 4.8 (512)",
    "address": "Nicolet, QC",
    "photoURL": "https://www.nicolet.ca/images/lac-saint-pierre.jpg",
    "type": "Réserve de biosphère",
    "rating": 4.8
  },
  {
    "id": "spot-0045",
    "name": "Plage municipale de Nicolet",
    "latitude": 46.2167,
    "longitude": -72.6,
    "description": "Type: Plage | Note: 4.3 (61)",
    "address": "Nicolet, QC",
    "photoURL": "https://www.nicolet.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0046",
    "name": "Parc écologique de l’Anse du Port",
    "latitude": 46.2167,
    "longitude": -72.6,
    "description": "Type: Parc écologique | Note: 4.6 (278)",
    "address": "Nicolet, QC",
    "photoURL": "https://www.nicolet.ca/images/parc-anse-du-port.jpg",
    "type": "Parc écologique",
    "rating": 4.6
  },
  {
    "id": "spot-0047",
    "name": "Plage municipale de Bécancour",
    "latitude": 46.3333,
    "longitude": -72.4333,
    "description": "Type: Plage | Note: 4.4 (73)",
    "address": "Bécancour, QC",
    "photoURL": "https://www.becancour.net/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0048",
    "name": "Parc de la rivière Gentilly",
    "latitude": 46.3667,
    "longitude": -72.2167,
    "description": "Type: Parc régional | Note: 4.7 (342)",
    "address": "Bécancour, QC",
    "photoURL": "https://www.rivieregentilly.com/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0049",
    "name": "Plage municipale de Saint-Grégoire",
    "latitude": 46.3167,
    "longitude": -72.4,
    "description": "Type: Plage | Note: 4.2 (39)",
    "address": "Saint-Grégoire, QC",
    "photoURL": "https://www.becancour.net/images/plage-saint-gregoire.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0050",
    "name": "Lac à la Tortue",
    "latitude": 46.5,
    "longitude": -72.8,
    "description": "Type: Lac | Note: 4.5 (84)",
    "address": "Shawinigan, QC",
    "photoURL": "https://www.shawinigan.ca/images/lac-a-la-tortue.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0051",
    "name": "Plage municipale de Saint-Étienne-des-Grès",
    "latitude": 46.4333,
    "longitude": -72.8,
    "description": "Type: Plage | Note: 4.3 (49)",
    "address": "Saint-Étienne-des-Grès, QC",
    "photoURL": "https://www.st-etienne-des-gres.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0052",
    "name": "Parc de l’Île Melville",
    "latitude": 46.5333,
    "longitude": -72.75,
    "description": "Type: Parc régional | Note: 4.7 (512)",
    "address": "Shawinigan, QC",
    "photoURL": "https://www.shawinigan.ca/images/ile-melville.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0053",
    "name": "Plage municipale de Saint-Boniface",
    "latitude": 46.4667,
    "longitude": -72.7333,
    "description": "Type: Plage | Note: 4.2 (37)",
    "address": "Saint-Boniface, QC",
    "photoURL": "https://www.st-boniface.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0054",
    "name": "Lac à la Perchaude",
    "latitude": 46.55,
    "longitude": -72.7,
    "description": "Type: Lac | Note: 4.6 (63)",
    "address": "Saint-Mathieu-du-Parc, QC",
    "photoURL": "https://www.stmathieuduparc.ca/images/lac-perchaude.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0055",
    "name": "Plage municipale de Saint-Paulin",
    "latitude": 46.4167,
    "longitude": -72.8833,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Saint-Paulin, QC",
    "photoURL": "https://www.st-paulin.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0056",
    "name": "Parc régional de la rivière Batiscan",
    "latitude": 46.6667,
    "longitude": -72.4,
    "description": "Type: Parc régional | Note: 4.8 (389)",
    "address": "Saint-Narcisse, QC",
    "photoURL": "https://www.rivierebatiscan.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0057",
    "name": "Plage municipale de Saint-Narcisse",
    "latitude": 46.6667,
    "longitude": -72.4,
    "description": "Type: Plage | Note: 4.2 (36)",
    "address": "Saint-Narcisse, QC",
    "photoURL": "https://www.st-narcisse.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0058",
    "name": "Lac Sept Îles",
    "latitude": 46.8333,
    "longitude": -71.4,
    "description": "Type: Lac | Note: 4.7 (91)",
    "address": "Saint-Raymond, QC",
    "photoURL": "https://www.saint-raymond.ca/images/lac-sept-iles.jpg",
    "type": "Lac",
    "rating": 4.7
  },
  {
    "id": "spot-0059",
    "name": "Plage municipale de Saint-Raymond",
    "latitude": 46.8333,
    "longitude": -71.4,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Saint-Raymond, QC",
    "photoURL": "https://www.saint-raymond.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0060",
    "name": "Parc naturel régional de Portneuf",
    "latitude": 46.75,
    "longitude": -71.5,
    "description": "Type: Parc régional | Note: 4.8 (512)",
    "address": "Portneuf, QC",
    "photoURL": "https://www.portneuf.ca/images/parc-naturel.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0061",
    "name": "Plage municipale de Saint-Léonard-de-Portneuf",
    "latitude": 46.85,
    "longitude": -71.6,
    "description": "Type: Plage | Note: 4.3 (45)",
    "address": "Saint-Léonard-de-Portneuf, QC",
    "photoURL": "https://www.st-leonard-portneuf.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0062",
    "name": "Lac Sergent",
    "latitude": 46.8833,
    "longitude": -71.65,
    "description": "Type: Lac | Note: 4.6 (67)",
    "address": "Lac-Sergent, QC",
    "photoURL": "https://www.lac-sergent.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0063",
    "name": "Plage municipale de Lac-Sergent",
    "latitude": 46.8833,
    "longitude": -71.65,
    "description": "Type: Plage | Note: 4.4 (52)",
    "address": "Lac-Sergent, QC",
    "photoURL": "https://www.lac-sergent.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0064",
    "name": "Parc naturel de la Jacques-Cartier",
    "latitude": 47,
    "longitude": -71.4,
    "description": "Type: Parc national | Note: 4.8 (1345)",
    "address": "Stoneham-et-Tewkesbury, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/jacques-cartier/parc.jpg",
    "type": "Parc national",
    "rating": 4.8
  },
  {
    "id": "spot-0065",
    "name": "Plage municipale de Stoneham",
    "latitude": 47,
    "longitude": -71.4,
    "description": "Type: Plage | Note: 4.2 (39)",
    "address": "Stoneham-et-Tewkesbury, QC",
    "photoURL": "https://www.stoneham.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0066",
    "name": "Lac Beauport",
    "latitude": 47,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.7 (89)",
    "address": "Lac-Beauport, QC",
    "photoURL": "https://www.lac-beauport.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.7
  },
  {
    "id": "spot-0067",
    "name": "Plage municipale de Lac-Beauport",
    "latitude": 47,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.5 (63)",
    "address": "Lac-Beauport, QC",
    "photoURL": "https://www.lac-beauport.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0068",
    "name": "Parc du Mont Wright",
    "latitude": 47.0333,
    "longitude": -71.35,
    "description": "Type: Parc naturel | Note: 4.6 (278)",
    "address": "Stoneham-et-Tewkesbury, QC",
    "photoURL": "https://www.stoneham.qc.ca/images/mont-wright.jpg",
    "type": "Parc naturel",
    "rating": 4.6
  },
  {
    "id": "spot-0069",
    "name": "Plage municipale de Sainte-Brigitte-de-Laval",
    "latitude": 47.05,
    "longitude": -71.25,
    "description": "Type: Plage | Note: 4.3 (41)",
    "address": "Sainte-Brigitte-de-Laval, QC",
    "photoURL": "https://www.sainte-brigitte.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0070",
    "name": "Lac des Roches",
    "latitude": 47.0667,
    "longitude": -71.2333,
    "description": "Type: Lac | Note: 4.5 (54)",
    "address": "Sainte-Brigitte-de-Laval, QC",
    "photoURL": "https://www.sainte-brigitte.qc.ca/images/lac-des-roches.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0071",
    "name": "Plage municipale de Saint-Apollinaire",
    "latitude": 46.6167,
    "longitude": -71.5167,
    "description": "Type: Plage | Note: 4.3 (48)",
    "address": "Saint-Apollinaire, QC",
    "photoURL": "https://www.saint-apollinaire.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0072",
    "name": "Lac Saint-Augustin",
    "latitude": 46.75,
    "longitude": -71.3667,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Augustin-de-Desmaures, QC",
    "photoURL": "https://www.ville.saint-augustin.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0073",
    "name": "Plage municipale de Saint-Augustin",
    "latitude": 46.75,
    "longitude": -71.3667,
    "description": "Type: Plage | Note: 4.4 (55)",
    "address": "Saint-Augustin-de-Desmaures, QC",
    "photoURL": "https://www.ville.saint-augustin.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0074",
    "name": "Parc de la Plage-Jacques-Cartier",
    "latitude": 46.7333,
    "longitude": -71.3,
    "description": "Type: Parc | Note: 4.7 (812)",
    "address": "Cap-Rouge, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/parc-jacques-cartier.jpg",
    "type": "Parc",
    "rating": 4.7
  },
  {
    "id": "spot-0075",
    "name": "Plage municipale de Cap-Rouge",
    "latitude": 46.7333,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.3 (61)",
    "address": "Cap-Rouge, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-cap-rouge.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0076",
    "name": "Lac Saint-Charles",
    "latitude": 47,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.6 (89)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/lac-saint-charles.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0077",
    "name": "Plage municipale de Saint-Charles",
    "latitude": 47,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-saint-charles.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0078",
    "name": "Parc naturel du Marais du Nord",
    "latitude": 47.05,
    "longitude": -71.3,
    "description": "Type: Parc naturel | Note: 4.8 (623)",
    "address": "Québec, QC",
    "photoURL": "https://www.maraisdunord.qc.ca/images/parc.jpg",
    "type": "Parc naturel",
    "rating": 4.8
  },
  {
    "id": "spot-0079",
    "name": "Plage municipale de Lac-Delage",
    "latitude": 47.1,
    "longitude": -71.35,
    "description": "Type: Plage | Note: 4.3 (47)",
    "address": "Lac-Delage, QC",
    "photoURL": "https://www.lac-delage.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0080",
    "name": "Lac Delage",
    "latitude": 47.1,
    "longitude": -71.35,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Lac-Delage, QC",
    "photoURL": "https://www.lac-delage.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0081",
    "name": "Plage municipale de Shannon",
    "latitude": 46.9,
    "longitude": -71.5,
    "description": "Type: Plage | Note: 4.3 (46)",
    "address": "Shannon, QC",
    "photoURL": "https://www.shannon.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0082",
    "name": "Lac Saint-Joseph (secteur Duchesnay)",
    "latitude": 46.8833,
    "longitude": -71.5,
    "description": "Type: Lac | Note: 4.7 (94)",
    "address": "Sainte-Catherine-de-la-Jacques-Cartier, QC",
    "photoURL": "https://www.sepaq.com/resources/images/duchesnay/lac-saint-joseph.jpg",
    "type": "Lac",
    "rating": 4.7
  },
  {
    "id": "spot-0083",
    "name": "Plage municipale de Sainte-Catherine-de-la-Jacques-Cartier",
    "latitude": 46.8833,
    "longitude": -71.5,
    "description": "Type: Plage | Note: 4.4 (59)",
    "address": "Sainte-Catherine-de-la-Jacques-Cartier, QC",
    "photoURL": "https://www.ville.scjc.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0084",
    "name": "Parc naturel du Grand Héron",
    "latitude": 46.9,
    "longitude": -71.45,
    "description": "Type: Parc naturel | Note: 4.6 (278)",
    "address": "Sainte-Catherine-de-la-Jacques-Cartier, QC",
    "photoURL": "https://www.ville.scjc.qc.ca/images/parc-grand-heron.jpg",
    "type": "Parc naturel",
    "rating": 4.6
  },
  {
    "id": "spot-0085",
    "name": "Plage municipale de Fossambault-sur-le-Lac",
    "latitude": 46.8833,
    "longitude": -71.5,
    "description": "Type: Plage | Note: 4.5 (63)",
    "address": "Fossambault-sur-le-Lac, QC",
    "photoURL": "https://www.fossambault-sur-le-lac.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0086",
    "name": "Lac Saint-Joseph (secteur Fossambault)",
    "latitude": 46.8833,
    "longitude": -71.5,
    "description": "Type: Lac | Note: 4.6 (88)",
    "address": "Fossambault-sur-le-Lac, QC",
    "photoURL": "https://www.fossambault-sur-le-lac.com/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0087",
    "name": "Parc du Domaine de la Faune",
    "latitude": 46.85,
    "longitude": -71.3,
    "description": "Type: Parc | Note: 4.7 (312)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/parc-faune.jpg",
    "type": "Parc",
    "rating": 4.7
  },
  {
    "id": "spot-0088",
    "name": "Plage municipale de Val-Bélair",
    "latitude": 46.85,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Val-Bélair, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-val-belair.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0089",
    "name": "Lac Saint-Charles (secteur nord)",
    "latitude": 47.05,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.6 (74)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/lac-saint-charles-nord.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0090",
    "name": "Plage municipale de Lac-Saint-Charles",
    "latitude": 47.05,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-lac-saint-charles.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0091",
    "name": "Plage municipale de Saint-Émile",
    "latitude": 46.9,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.3 (44)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-saint-emile.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0092",
    "name": "Lac Saint-Émile",
    "latitude": 46.9,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.6 (68)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/lac-saint-emile.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0093",
    "name": "Parc de la Rivière Saint-Charles",
    "latitude": 46.85,
    "longitude": -71.25,
    "description": "Type: Parc | Note: 4.7 (812)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/parc-riviere-saint-charles.jpg",
    "type": "Parc",
    "rating": 4.7
  },
  {
    "id": "spot-0094",
    "name": "Plage municipale de Loretteville",
    "latitude": 46.85,
    "longitude": -71.25,
    "description": "Type: Plage | Note: 4.2 (39)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-loretteville.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0095",
    "name": "Lac des Roches (secteur nord)",
    "latitude": 47.0667,
    "longitude": -71.2333,
    "description": "Type: Lac | Note: 4.5 (54)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/lac-des-roches-nord.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0096",
    "name": "Plage municipale de Charlesbourg",
    "latitude": 46.8667,
    "longitude": -71.2333,
    "description": "Type: Plage | Note: 4.3 (41)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-charlesbourg.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0097",
    "name": "Parc de la Montagne-des-Roches",
    "latitude": 46.8667,
    "longitude": -71.2333,
    "description": "Type: Parc naturel | Note: 4.6 (278)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/parc-montagne-des-roches.jpg",
    "type": "Parc naturel",
    "rating": 4.6
  },
  {
    "id": "spot-0098",
    "name": "Plage municipale de Beauport",
    "latitude": 46.8667,
    "longitude": -71.2,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Québec, QC",
    "photoURL": "https://www.ville.quebec.qc.ca/images/plage-beauport.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0099",
    "name": "Baie de Beauport",
    "latitude": 46.8667,
    "longitude": -71.2,
    "description": "Type: Plage | Note: 4.6 (623)",
    "address": "Québec, QC",
    "photoURL": "https://www.baiedebeauport.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.6
  },
  {
    "id": "spot-0100",
    "name": "Parc de la Chute-Montmorency",
    "latitude": 46.9,
    "longitude": -71.15,
    "description": "Type: Parc | Note: 4.8 (1345)",
    "address": "Boischatel, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parcs/chute-montmorency.jpg",
    "type": "Parc",
    "rating": 4.8
  },
  {
    "id": "spot-0101",
    "name": "Plage municipale de Boischatel",
    "latitude": 46.9,
    "longitude": -71.15,
    "description": "Type: Plage | Note: 4.3 (47)",
    "address": "Boischatel, QC",
    "photoURL": "https://www.boischatel.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0102",
    "name": "Lac Beauport (secteur nord)",
    "latitude": 47.05,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Lac-Beauport, QC",
    "photoURL": "https://www.lac-beauport.ca/images/lac-nord.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0103",
    "name": "Plage municipale de Lac-Beauport (secteur nord)",
    "latitude": 47.05,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Lac-Beauport, QC",
    "photoURL": "https://www.lac-beauport.ca/images/plage-nord.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0104",
    "name": "Parc du Mont-Tourbillon",
    "latitude": 47.0667,
    "longitude": -71.3167,
    "description": "Type: Parc naturel | Note: 4.7 (312)",
    "address": "Lac-Beauport, QC",
    "photoURL": "https://www.lac-beauport.ca/images/mont-tourbillon.jpg",
    "type": "Parc naturel",
    "rating": 4.7
  },
  {
    "id": "spot-0105",
    "name": "Plage municipale de Sainte-Brigitte-de-Laval (secteur est)",
    "latitude": 47.0667,
    "longitude": -71.2333,
    "description": "Type: Plage | Note: 4.3 (41)",
    "address": "Sainte-Brigitte-de-Laval, QC",
    "photoURL": "https://www.sainte-brigitte.qc.ca/images/plage-est.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0106",
    "name": "Lac des Roches (secteur est)",
    "latitude": 47.0667,
    "longitude": -71.2333,
    "description": "Type: Lac | Note: 4.5 (54)",
    "address": "Sainte-Brigitte-de-Laval, QC",
    "photoURL": "https://www.sainte-brigitte.qc.ca/images/lac-des-roches-est.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0107",
    "name": "Parc du Mont Brillant",
    "latitude": 47.0833,
    "longitude": -71.25,
    "description": "Type: Parc naturel | Note: 4.6 (278)",
    "address": "Sainte-Brigitte-de-Laval, QC",
    "photoURL": "https://www.sainte-brigitte.qc.ca/images/mont-brillant.jpg",
    "type": "Parc naturel",
    "rating": 4.6
  },
  {
    "id": "spot-0108",
    "name": "Plage municipale de Saint-Ferréol-les-Neiges (secteur nord)",
    "latitude": 47.1,
    "longitude": -70.8833,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Saint-Ferréol-les-Neiges, QC",
    "photoURL": "https://www.stferreollesneiges.ca/images/plage-nord.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0109",
    "name": "Lac Saint-Ferréol",
    "latitude": 47.1,
    "longitude": -70.8833,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Ferréol-les-Neiges, QC",
    "photoURL": "https://www.stferreollesneiges.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0110",
    "name": "Parc du Mont-Saint-Anne",
    "latitude": 47.1,
    "longitude": -70.9,
    "description": "Type: Parc naturel | Note: 4.8 (1345)",
    "address": "Beaupré, QC",
    "photoURL": "https://www.mont-sainte-anne.com/images/parc.jpg",
    "type": "Parc naturel",
    "rating": 4.8
  },
  {
    "id": "spot-0111",
    "name": "Plage municipale de Beaupré",
    "latitude": 47.05,
    "longitude": -70.9,
    "description": "Type: Plage | Note: 4.3 (49)",
    "address": "Beaupré, QC",
    "photoURL": "https://www.ville.beaupre.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0112",
    "name": "Lac Beaupré",
    "latitude": 47.05,
    "longitude": -70.9,
    "description": "Type: Lac | Note: 4.6 (71)",
    "address": "Beaupré, QC",
    "photoURL": "https://www.ville.beaupre.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0113",
    "name": "Parc du Mont Sainte-Anne",
    "latitude": 47.1,
    "longitude": -70.9,
    "description": "Type: Parc naturel | Note: 4.8 (1345)",
    "address": "Beaupré, QC",
    "photoURL": "https://www.mont-sainte-anne.com/images/parc.jpg",
    "type": "Parc naturel",
    "rating": 4.8
  },
  {
    "id": "spot-0114",
    "name": "Plage municipale de Saint-Tite-des-Caps",
    "latitude": 47.1833,
    "longitude": -70.8,
    "description": "Type: Plage | Note: 4.2 (38)",
    "address": "Saint-Tite-des-Caps, QC",
    "photoURL": "https://www.sainttitedescaps.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0115",
    "name": "Lac Saint-Tite",
    "latitude": 47.1833,
    "longitude": -70.8,
    "description": "Type: Lac | Note: 4.5 (56)",
    "address": "Saint-Tite-des-Caps, QC",
    "photoURL": "https://www.sainttitedescaps.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0116",
    "name": "Parc naturel du Massif de Charlevoix",
    "latitude": 47.25,
    "longitude": -70.7,
    "description": "Type: Parc naturel | Note: 4.7 (623)",
    "address": "Petite-Rivière-Saint-François, QC",
    "photoURL": "https://www.lemassif.com/images/parc.jpg",
    "type": "Parc naturel",
    "rating": 4.7
  },
  {
    "id": "spot-0117",
    "name": "Plage municipale de Petite-Rivière-Saint-François",
    "latitude": 47.25,
    "longitude": -70.7,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Petite-Rivière-Saint-François, QC",
    "photoURL": "https://www.petiteriviere.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0118",
    "name": "Lac à l'Écluse",
    "latitude": 47.3,
    "longitude": -70.65,
    "description": "Type: Lac | Note: 4.6 (64)",
    "address": "Petite-Rivière-Saint-François, QC",
    "photoURL": "https://www.petiteriviere.qc.ca/images/lac-ecluse.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0119",
    "name": "Parc régional de la Baie-Saint-Paul",
    "latitude": 47.3833,
    "longitude": -70.6,
    "description": "Type: Parc régional | Note: 4.8 (389)",
    "address": "Baie-Saint-Paul, QC",
    "photoURL": "https://www.baiesaintpaul.com/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0120",
    "name": "Plage municipale de Baie-Saint-Paul",
    "latitude": 47.3833,
    "longitude": -70.6,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Baie-Saint-Paul, QC",
    "photoURL": "https://www.baiesaintpaul.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0121",
    "name": "Plage municipale de Saint-Irénée",
    "latitude": 47.5,
    "longitude": -70.3,
    "description": "Type: Plage | Note: 4.4 (51)",
    "address": "Saint-Irénée, QC",
    "photoURL": "https://www.saint-irenee.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0122",
    "name": "Lac Saint-Irénée",
    "latitude": 47.5,
    "longitude": -70.3,
    "description": "Type: Lac | Note: 4.6 (68)",
    "address": "Saint-Irénée, QC",
    "photoURL": "https://www.saint-irenee.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0123",
    "name": "Parc régional des Grands-Jardins",
    "latitude": 47.5833,
    "longitude": -70.2,
    "description": "Type: Parc régional | Note: 4.8 (1345)",
    "address": "Saint-Urbain, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/grands-jardins/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0124",
    "name": "Plage municipale de Saint-Urbain",
    "latitude": 47.5833,
    "longitude": -70.2,
    "description": "Type: Plage | Note: 4.2 (39)",
    "address": "Saint-Urbain, QC",
    "photoURL": "https://www.saint-urbain.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.2
  },
  {
    "id": "spot-0125",
    "name": "Lac Saint-Urbain",
    "latitude": 47.5833,
    "longitude": -70.2,
    "description": "Type: Lac | Note: 4.5 (54)",
    "address": "Saint-Urbain, QC",
    "photoURL": "https://www.saint-urbain.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0126",
    "name": "Parc national des Hautes-Gorges-de-la-Rivière-Malbaie",
    "latitude": 47.75,
    "longitude": -70.1,
    "description": "Type: Parc national | Note: 4.9 (1456)",
    "address": "Saint-Aimé-des-Lacs, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/hautes-gorges/parc.jpg",
    "type": "Parc national",
    "rating": 4.9
  },
  {
    "id": "spot-0127",
    "name": "Plage municipale de Saint-Aimé-des-Lacs",
    "latitude": 47.75,
    "longitude": -70.2167,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Aimé-des-Lacs, QC",
    "photoURL": "https://www.st-aime-des-lacs.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0128",
    "name": "Lac Nairne",
    "latitude": 47.7667,
    "longitude": -70.2,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-Aimé-des-Lacs, QC",
    "photoURL": "https://www.st-aime-des-lacs.qc.ca/images/lac-nairne.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0129",
    "name": "Parc régional de la ZEC des Martres",
    "latitude": 47.8,
    "longitude": -70,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Charlevoix, QC",
    "photoURL": "https://www.zecdesmartres.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0130",
    "name": "Plage municipale de Charlevoix",
    "latitude": 47.8,
    "longitude": -70,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Charlevoix, QC",
    "photoURL": "https://www.charlevoix.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0131",
    "name": "Plage municipale de La Malbaie",
    "latitude": 47.65,
    "longitude": -70.15,
    "description": "Type: Plage | Note: 4.4 (57)",
    "address": "La Malbaie, QC",
    "photoURL": "https://www.ville.lamalbaie.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0132",
    "name": "Lac de La Malbaie",
    "latitude": 47.65,
    "longitude": -70.15,
    "description": "Type: Lac | Note: 4.6 (73)",
    "address": "La Malbaie, QC",
    "photoURL": "https://www.ville.lamalbaie.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0133",
    "name": "Parc du Mont Grand-Fonds",
    "latitude": 47.7,
    "longitude": -70.1,
    "description": "Type: Parc naturel | Note: 4.7 (623)",
    "address": "La Malbaie, QC",
    "photoURL": "https://www.montgrandfonds.com/images/parc.jpg",
    "type": "Parc naturel",
    "rating": 4.7
  },
  {
    "id": "spot-0134",
    "name": "Plage municipale de Clermont",
    "latitude": 47.6833,
    "longitude": -70.2,
    "description": "Type: Plage | Note: 4.3 (44)",
    "address": "Clermont, QC",
    "photoURL": "https://www.ville.clermont.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0135",
    "name": "Lac Clermont",
    "latitude": 47.6833,
    "longitude": -70.2,
    "description": "Type: Lac | Note: 4.5 (61)",
    "address": "Clermont, QC",
    "photoURL": "https://www.ville.clermont.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0136",
    "name": "Parc régional de Port-au-Saumon",
    "latitude": 47.75,
    "longitude": -69.95,
    "description": "Type: Parc régional | Note: 4.8 (389)",
    "address": "Charlevoix-Est, QC",
    "photoURL": "https://www.portausaumon.com/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0137",
    "name": "Plage municipale de Port-au-Saumon",
    "latitude": 47.75,
    "longitude": -69.95,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Charlevoix-Est, QC",
    "photoURL": "https://www.portausaumon.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0138",
    "name": "Lac Port-au-Saumon",
    "latitude": 47.75,
    "longitude": -69.95,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Charlevoix-Est, QC",
    "photoURL": "https://www.portausaumon.com/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0139",
    "name": "Parc national des Monts-Valin",
    "latitude": 48.5,
    "longitude": -70,
    "description": "Type: Parc national | Note: 4.9 (1456)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/monts-valin/parc.jpg",
    "type": "Parc national",
    "rating": 4.9
  },
  {
    "id": "spot-0140",
    "name": "Plage municipale de Saguenay",
    "latitude": 48.4167,
    "longitude": -71.0667,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.ville.saguenay.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0141",
    "name": "Lac Kénogami",
    "latitude": 48.4333,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.7 (94)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.saguenay.ca/images/lac-kenogami.jpg",
    "type": "Lac",
    "rating": 4.7
  },
  {
    "id": "spot-0142",
    "name": "Plage municipale de Jonquière",
    "latitude": 48.4167,
    "longitude": -71.25,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.saguenay.ca/images/plage-jonquiere.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0143",
    "name": "Parc de la Rivière-du-Moulin",
    "latitude": 48.4167,
    "longitude": -71.0667,
    "description": "Type: Parc | Note: 4.8 (623)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.saguenay.ca/images/parc-riviere-du-moulin.jpg",
    "type": "Parc",
    "rating": 4.8
  },
  {
    "id": "spot-0144",
    "name": "Plage municipale de Chicoutimi",
    "latitude": 48.4167,
    "longitude": -71.0667,
    "description": "Type: Plage | Note: 4.3 (47)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.saguenay.ca/images/plage-chicoutimi.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0145",
    "name": "Lac Sébastien",
    "latitude": 48.5,
    "longitude": -70.9,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Saguenay, QC",
    "photoURL": "https://www.saguenay.ca/images/lac-sebastien.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0146",
    "name": "Plage municipale de Saint-David-de-Falardeau",
    "latitude": 48.55,
    "longitude": -70.9,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Saint-David-de-Falardeau, QC",
    "photoURL": "https://www.st-david.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0147",
    "name": "Parc national des Monts-Valin (secteur Falardeau)",
    "latitude": 48.5833,
    "longitude": -70.85,
    "description": "Type: Parc national | Note: 4.9 (1456)",
    "address": "Saint-David-de-Falardeau, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/monts-valin/falardeau.jpg",
    "type": "Parc national",
    "rating": 4.9
  },
  {
    "id": "spot-0148",
    "name": "Lac des Cèdres",
    "latitude": 48.6,
    "longitude": -70.8,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-David-de-Falardeau, QC",
    "photoURL": "https://www.st-david.qc.ca/images/lac-des-cedres.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0149",
    "name": "Plage municipale de Saint-Fulgence",
    "latitude": 48.5,
    "longitude": -70.75,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Saint-Fulgence, QC",
    "photoURL": "https://www.st-fulgence.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0150",
    "name": "Lac Saint-Fulgence",
    "latitude": 48.5,
    "longitude": -70.75,
    "description": "Type: Lac | Note: 4.5 (61)",
    "address": "Saint-Fulgence, QC",
    "photoURL": "https://www.st-fulgence.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0151",
    "name": "Parc Aventures Cap Jaseux",
    "latitude": 48.4167,
    "longitude": -70.8,
    "description": "Type: Parc d'aventure | Note: 4.7 (512)",
    "address": "Saint-Fulgence, QC",
    "photoURL": "https://www.capjaseux.com/images/parc.jpg",
    "type": "Parc d'aventure",
    "rating": 4.7
  },
  {
    "id": "spot-0152",
    "name": "Plage du Cap Jaseux",
    "latitude": 48.4167,
    "longitude": -70.8,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Fulgence, QC",
    "photoURL": "https://www.capjaseux.com/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0153",
    "name": "Lac Tchitogama",
    "latitude": 48.6667,
    "longitude": -71,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Lamarche, QC",
    "photoURL": "https://www.lamarche.ca/images/lac-tchitogama.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0154",
    "name": "Plage municipale de Lamarche",
    "latitude": 48.6667,
    "longitude": -71,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Lamarche, QC",
    "photoURL": "https://www.lamarche.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0155",
    "name": "Parc régional des Grandes-Rivières du Lac Saint-Jean",
    "latitude": 48.6667,
    "longitude": -71.25,
    "description": "Type: Parc régional | Note: 4.8 (389)",
    "address": "Alma, QC",
    "photoURL": "https://www.ville.alma.qc.ca/images/parc-grandes-rivieres.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0156",
    "name": "Plage municipale d'Alma",
    "latitude": 48.55,
    "longitude": -71.25,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Alma, QC",
    "photoURL": "https://www.ville.alma.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0157",
    "name": "Lac Saint-Jean",
    "latitude": 48.5,
    "longitude": -71.5,
    "description": "Type: Lac | Note: 4.9 (1456)",
    "address": "Lac-Saint-Jean, QC",
    "photoURL": "https://www.lacsaintjean.com/images/lac.jpg",
    "type": "Lac",
    "rating": 4.9
  },
  {
    "id": "spot-0158",
    "name": "Plage municipale de Saint-Gédéon",
    "latitude": 48.4833,
    "longitude": -71.6,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Gédéon, QC",
    "photoURL": "https://www.st-gedeon.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0159",
    "name": "Parc national de la Pointe-Taillon",
    "latitude": 48.5833,
    "longitude": -71.6667,
    "description": "Type: Parc national | Note: 4.8 (1345)",
    "address": "Saint-Henri-de-Taillon, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/pointe-taillon/parc.jpg",
    "type": "Parc national",
    "rating": 4.8
  },
  {
    "id": "spot-0160",
    "name": "Plage de la Pointe-Taillon",
    "latitude": 48.5833,
    "longitude": -71.6667,
    "description": "Type: Plage | Note: 4.6 (89)",
    "address": "Saint-Henri-de-Taillon, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/pointe-taillon/plage.jpg",
    "type": "Plage",
    "rating": 4.6
  },
  {
    "id": "spot-0161",
    "name": "Plage municipale de Péribonka",
    "latitude": 48.8333,
    "longitude": -71.2,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Péribonka, QC",
    "photoURL": "https://www.peribonka.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0162",
    "name": "Lac Péribonka",
    "latitude": 48.8333,
    "longitude": -71.2,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Péribonka, QC",
    "photoURL": "https://www.peribonka.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0163",
    "name": "Parc régional des Monts-Valin (secteur nord)",
    "latitude": 48.9,
    "longitude": -70.9,
    "description": "Type: Parc régional | Note: 4.8 (1345)",
    "address": "Monts-Valin, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/monts-valin/nord.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0164",
    "name": "Plage municipale de Sainte-Monique",
    "latitude": 48.9,
    "longitude": -71.3,
    "description": "Type: Plage | Note: 4.3 (42)",
    "address": "Sainte-Monique, QC",
    "photoURL": "https://www.sainte-monique.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.3
  },
  {
    "id": "spot-0165",
    "name": "Lac Sainte-Monique",
    "latitude": 48.9,
    "longitude": -71.3,
    "description": "Type: Lac | Note: 4.5 (61)",
    "address": "Sainte-Monique, QC",
    "photoURL": "https://www.sainte-monique.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.5
  },
  {
    "id": "spot-0166",
    "name": "Parc régional de la Chute à l’Ours",
    "latitude": 49,
    "longitude": -72,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Normandin, QC",
    "photoURL": "https://www.normandin.qc.ca/images/chute-ours.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0167",
    "name": "Plage municipale de Normandin",
    "latitude": 49,
    "longitude": -72,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Normandin, QC",
    "photoURL": "https://www.normandin.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0168",
    "name": "Lac Normandin",
    "latitude": 49,
    "longitude": -72,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Normandin, QC",
    "photoURL": "https://www.normandin.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0169",
    "name": "Parc régional de la Pointe-Bleue",
    "latitude": 49.1,
    "longitude": -72.1,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Mashteuiatsh, QC",
    "photoURL": "https://www.mashteuiatsh.ca/images/parc-pointe-bleue.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0170",
    "name": "Plage municipale de Mashteuiatsh",
    "latitude": 49.1,
    "longitude": -72.1,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Mashteuiatsh, QC",
    "photoURL": "https://www.mashteuiatsh.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0171",
    "name": "Lac Mashteuiatsh",
    "latitude": 49.1,
    "longitude": -72.1,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Mashteuiatsh, QC",
    "photoURL": "https://www.mashteuiatsh.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0172",
    "name": "Parc régional de Dolbeau-Mistassini",
    "latitude": 49.2167,
    "longitude": -72.2333,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Dolbeau-Mistassini, QC",
    "photoURL": "https://www.dolbeau-mistassini.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0173",
    "name": "Plage municipale de Dolbeau-Mistassini",
    "latitude": 49.2167,
    "longitude": -72.2333,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Dolbeau-Mistassini, QC",
    "photoURL": "https://www.dolbeau-mistassini.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0174",
    "name": "Lac Mistassini",
    "latitude": 49.2167,
    "longitude": -72.2333,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Dolbeau-Mistassini, QC",
    "photoURL": "https://www.dolbeau-mistassini.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0175",
    "name": "Parc régional de Saint-Félicien",
    "latitude": 48.65,
    "longitude": -72.45,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-Félicien, QC",
    "photoURL": "https://www.stfelicien.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0176",
    "name": "Plage municipale de Saint-Félicien",
    "latitude": 48.65,
    "longitude": -72.45,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Félicien, QC",
    "photoURL": "https://www.stfelicien.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0177",
    "name": "Lac Saint-Félicien",
    "latitude": 48.65,
    "longitude": -72.45,
    "description": "Type: Lac | Note: 4.6 (89)",
    "address": "Saint-Félicien, QC",
    "photoURL": "https://www.stfelicien.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0178",
    "name": "Parc de la Pointe-des-Américains",
    "latitude": 48.6667,
    "longitude": -72.4667,
    "description": "Type: Parc | Note: 4.7 (312)",
    "address": "Saint-Félicien, QC",
    "photoURL": "https://www.stfelicien.qc.ca/images/pointe-americains.jpg",
    "type": "Parc",
    "rating": 4.7
  },
  {
    "id": "spot-0179",
    "name": "Plage municipale de Roberval",
    "latitude": 48.5167,
    "longitude": -72.2333,
    "description": "Type: Plage | Note: 4.4 (58)",
    "address": "Roberval, QC",
    "photoURL": "https://www.roberval.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0180",
    "name": "Lac Roberval",
    "latitude": 48.5167,
    "longitude": -72.2333,
    "description": "Type: Lac | Note: 4.6 (66)",
    "address": "Roberval, QC",
    "photoURL": "https://www.roberval.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0181",
    "name": "Parc régional de Val-Jalbert",
    "latitude": 48.4167,
    "longitude": -72.2333,
    "description": "Type: Parc régional | Note: 4.8 (1345)",
    "address": "Chambord, QC",
    "photoURL": "https://www.valjalbert.com/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0182",
    "name": "Plage municipale de Chambord",
    "latitude": 48.4167,
    "longitude": -72.2333,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Chambord, QC",
    "photoURL": "https://www.chambord.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0183",
    "name": "Lac Chambord",
    "latitude": 48.4167,
    "longitude": -72.2333,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Chambord, QC",
    "photoURL": "https://www.chambord.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0184",
    "name": "Parc national de la Pointe-Taillon (secteur sud)",
    "latitude": 48.5,
    "longitude": -71.6667,
    "description": "Type: Parc national | Note: 4.9 (1456)",
    "address": "Saint-Henri-de-Taillon, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/pointe-taillon/sud.jpg",
    "type": "Parc national",
    "rating": 4.9
  },
  {
    "id": "spot-0185",
    "name": "Plage de Saint-Henri-de-Taillon",
    "latitude": 48.5,
    "longitude": -71.6667,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Henri-de-Taillon, QC",
    "photoURL": "https://www.st-henri.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0186",
    "name": "Lac Saint-Henri",
    "latitude": 48.5,
    "longitude": -71.6667,
    "description": "Type: Lac | Note: 4.6 (89)",
    "address": "Saint-Henri-de-Taillon, QC",
    "photoURL": "https://www.st-henri.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0187",
    "name": "Parc régional de Métabetchouan",
    "latitude": 48.4167,
    "longitude": -71.8667,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Métabetchouan–Lac-à-la-Croix, QC",
    "photoURL": "https://www.metabetchouan.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0188",
    "name": "Plage municipale de Métabetchouan",
    "latitude": 48.4167,
    "longitude": -71.8667,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Métabetchouan–Lac-à-la-Croix, QC",
    "photoURL": "https://www.metabetchouan.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0189",
    "name": "Lac à la Croix",
    "latitude": 48.4167,
    "longitude": -71.8667,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Métabetchouan–Lac-à-la-Croix, QC",
    "photoURL": "https://www.metabetchouan.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0190",
    "name": "Parc régional de Desbiens",
    "latitude": 48.4167,
    "longitude": -71.9333,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Desbiens, QC",
    "photoURL": "https://www.desbiens.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0191",
    "name": "Plage municipale de Desbiens",
    "latitude": 48.4167,
    "longitude": -71.9333,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Desbiens, QC",
    "photoURL": "https://www.desbiens.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0192",
    "name": "Lac Desbiens",
    "latitude": 48.4167,
    "longitude": -71.9333,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Desbiens, QC",
    "photoURL": "https://www.desbiens.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0193",
    "name": "Parc régional de Saint-André-du-Lac-Saint-Jean",
    "latitude": 48.5,
    "longitude": -72,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Saint-André-du-Lac-Saint-Jean, QC",
    "photoURL": "https://www.st-andre.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0194",
    "name": "Plage municipale de Saint-André-du-Lac-Saint-Jean",
    "latitude": 48.5,
    "longitude": -72,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-André-du-Lac-Saint-Jean, QC",
    "photoURL": "https://www.st-andre.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0195",
    "name": "Lac Saint-André",
    "latitude": 48.5,
    "longitude": -72,
    "description": "Type: Lac | Note: 4.6 (89)",
    "address": "Saint-André-du-Lac-Saint-Jean, QC",
    "photoURL": "https://www.st-andre.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0196",
    "name": "Parc régional de Saint-François-de-Sales",
    "latitude": 48.5667,
    "longitude": -72.1,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-François-de-Sales, QC",
    "photoURL": "https://www.st-francois.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0197",
    "name": "Plage municipale de Saint-François-de-Sales",
    "latitude": 48.5667,
    "longitude": -72.1,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-François-de-Sales, QC",
    "photoURL": "https://www.st-francois.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0198",
    "name": "Lac Saint-François",
    "latitude": 48.5667,
    "longitude": -72.1,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-François-de-Sales, QC",
    "photoURL": "https://www.st-francois.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0199",
    "name": "Parc régional de La Doré",
    "latitude": 48.6667,
    "longitude": -72.3,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "La Doré, QC",
    "photoURL": "https://www.ladore.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0200",
    "name": "Plage municipale de La Doré",
    "latitude": 48.6667,
    "longitude": -72.3,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "La Doré, QC",
    "photoURL": "https://www.ladore.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0201",
    "name": "Lac La Doré",
    "latitude": 48.6667,
    "longitude": -72.3,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "La Doré, QC",
    "photoURL": "https://www.ladore.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0202",
    "name": "Parc régional de Saint-Prime",
    "latitude": 48.6167,
    "longitude": -72.05,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-Prime, QC",
    "photoURL": "https://www.saint-prime.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0203",
    "name": "Plage municipale de Saint-Prime",
    "latitude": 48.6167,
    "longitude": -72.05,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Prime, QC",
    "photoURL": "https://www.saint-prime.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0204",
    "name": "Lac Saint-Prime",
    "latitude": 48.6167,
    "longitude": -72.05,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-Prime, QC",
    "photoURL": "https://www.saint-prime.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0205",
    "name": "Parc régional de Saint-Méthode",
    "latitude": 48.5667,
    "longitude": -72,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Saint-Méthode, QC",
    "photoURL": "https://www.st-methode.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0206",
    "name": "Plage municipale de Saint-Méthode",
    "latitude": 48.5667,
    "longitude": -72,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Saint-Méthode, QC",
    "photoURL": "https://www.st-methode.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0207",
    "name": "Lac Saint-Méthode",
    "latitude": 48.5667,
    "longitude": -72,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Méthode, QC",
    "photoURL": "https://www.st-methode.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0208",
    "name": "Parc régional de Saint-Thomas-Didyme",
    "latitude": 48.75,
    "longitude": -72.15,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Saint-Thomas-Didyme, QC",
    "photoURL": "https://www.st-thomas.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0209",
    "name": "Plage municipale de Saint-Thomas-Didyme",
    "latitude": 48.75,
    "longitude": -72.15,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Saint-Thomas-Didyme, QC",
    "photoURL": "https://www.st-thomas.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0210",
    "name": "Lac Saint-Thomas",
    "latitude": 48.75,
    "longitude": -72.15,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Thomas-Didyme, QC",
    "photoURL": "https://www.st-thomas.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0211",
    "name": "Lac Saint-Thomas-Didyme",
    "latitude": 48.75,
    "longitude": -72.15,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Thomas-Didyme, QC",
    "photoURL": "https://www.st-thomas.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0212",
    "name": "Parc régional de Girardville",
    "latitude": 48.8833,
    "longitude": -72.3,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Girardville, QC",
    "photoURL": "https://www.girardville.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0213",
    "name": "Plage municipale de Girardville",
    "latitude": 48.8833,
    "longitude": -72.3,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Girardville, QC",
    "photoURL": "https://www.girardville.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0214",
    "name": "Lac Girardville",
    "latitude": 48.8833,
    "longitude": -72.3,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Girardville, QC",
    "photoURL": "https://www.girardville.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0215",
    "name": "Parc régional de Saint-Stanislas",
    "latitude": 48.9333,
    "longitude": -72.4,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-Stanislas, QC",
    "photoURL": "https://www.st-stanislas.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0216",
    "name": "Plage municipale de Saint-Stanislas",
    "latitude": 48.9333,
    "longitude": -72.4,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Stanislas, QC",
    "photoURL": "https://www.st-stanislas.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0217",
    "name": "Lac Saint-Stanislas",
    "latitude": 48.9333,
    "longitude": -72.4,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-Stanislas, QC",
    "photoURL": "https://www.st-stanislas.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0218",
    "name": "Parc régional de Saint-Augustin",
    "latitude": 49,
    "longitude": -72.5,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Saint-Augustin, QC",
    "photoURL": "https://www.st-augustin.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0219",
    "name": "Plage municipale de Saint-Augustin",
    "latitude": 49,
    "longitude": -72.5,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Saint-Augustin, QC",
    "photoURL": "https://www.st-augustin.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0220",
    "name": "Lac Saint-Augustin",
    "latitude": 49,
    "longitude": -72.5,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Saint-Augustin, QC",
    "photoURL": "https://www.st-augustin.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0221",
    "name": "Parc régional de Saint-Jean-sur-Richelieu",
    "latitude": 45.3167,
    "longitude": -73.2667,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-Jean-sur-Richelieu, QC",
    "photoURL": "https://www.sjsr.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0222",
    "name": "Plage municipale de Saint-Jean-sur-Richelieu",
    "latitude": 45.3167,
    "longitude": -73.2667,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Jean-sur-Richelieu, QC",
    "photoURL": "https://www.sjsr.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0223",
    "name": "Lac Saint-Jean-sur-Richelieu",
    "latitude": 45.3167,
    "longitude": -73.2667,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-Jean-sur-Richelieu, QC",
    "photoURL": "https://www.sjsr.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0224",
    "name": "Parc régional de Venise-en-Québec",
    "latitude": 45.05,
    "longitude": -73.15,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Venise-en-Québec, QC",
    "photoURL": "https://www.veniseenquebec.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0225",
    "name": "Plage municipale de Venise-en-Québec",
    "latitude": 45.05,
    "longitude": -73.15,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Venise-en-Québec, QC",
    "photoURL": "https://www.veniseenquebec.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0226",
    "name": "Lac Champlain",
    "latitude": 45,
    "longitude": -73.25,
    "description": "Type: Lac | Note: 4.9 (1456)",
    "address": "Venise-en-Québec, QC",
    "photoURL": "https://www.veniseenquebec.ca/images/lac-champlain.jpg",
    "type": "Lac",
    "rating": 4.9
  },
  {
    "id": "spot-0227",
    "name": "Parc régional de Saint-Armand",
    "latitude": 45.0167,
    "longitude": -73.0667,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Saint-Armand, QC",
    "photoURL": "https://www.st-armand.qc.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0228",
    "name": "Plage municipale de Saint-Armand",
    "latitude": 45.0167,
    "longitude": -73.0667,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Saint-Armand, QC",
    "photoURL": "https://www.st-armand.qc.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0229",
    "name": "Lac Saint-Armand",
    "latitude": 45.0167,
    "longitude": -73.0667,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Saint-Armand, QC",
    "photoURL": "https://www.st-armand.qc.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0230",
    "name": "Parc régional de Bedford",
    "latitude": 45.1,
    "longitude": -72.9833,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Bedford, QC",
    "photoURL": "https://www.bedford.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0231",
    "name": "Parc régional de Bedford (secteur sud)",
    "latitude": 45.0833,
    "longitude": -72.9833,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Bedford, QC",
    "photoURL": "https://www.bedford.ca/images/parc-sud.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0232",
    "name": "Plage municipale de Bedford",
    "latitude": 45.0833,
    "longitude": -72.9833,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Bedford, QC",
    "photoURL": "https://www.bedford.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0233",
    "name": "Lac Bedford",
    "latitude": 45.0833,
    "longitude": -72.9833,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Bedford, QC",
    "photoURL": "https://www.bedford.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0234",
    "name": "Parc régional de Cowansville",
    "latitude": 45.2,
    "longitude": -72.75,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Cowansville, QC",
    "photoURL": "https://www.cowansville.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0235",
    "name": "Plage municipale de Cowansville",
    "latitude": 45.2,
    "longitude": -72.75,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Cowansville, QC",
    "photoURL": "https://www.cowansville.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0236",
    "name": "Lac Davignon",
    "latitude": 45.2,
    "longitude": -72.75,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Cowansville, QC",
    "photoURL": "https://www.cowansville.ca/images/lac-davignon.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0237",
    "name": "Parc régional de Bromont",
    "latitude": 45.3167,
    "longitude": -72.65,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Bromont, QC",
    "photoURL": "https://www.bromont.net/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0238",
    "name": "Plage municipale de Bromont",
    "latitude": 45.3167,
    "longitude": -72.65,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Bromont, QC",
    "photoURL": "https://www.bromont.net/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0239",
    "name": "Lac Bromont",
    "latitude": 45.3167,
    "longitude": -72.65,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Bromont, QC",
    "photoURL": "https://www.bromont.net/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0240",
    "name": "Parc régional de Waterloo",
    "latitude": 45.35,
    "longitude": -72.5167,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Waterloo, QC",
    "photoURL": "https://www.waterloo.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0241",
    "name": "Plage municipale de Waterloo",
    "latitude": 45.35,
    "longitude": -72.5167,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Waterloo, QC",
    "photoURL": "https://www.waterloo.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0242",
    "name": "Lac Waterloo",
    "latitude": 45.35,
    "longitude": -72.5167,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Waterloo, QC",
    "photoURL": "https://www.waterloo.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0243",
    "name": "Parc régional de Roxton Pond",
    "latitude": 45.3833,
    "longitude": -72.4667,
    "description": "Type: Parc régional | Note: 4.7 (389)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.roxtonpond.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.7
  },
  {
    "id": "spot-0244",
    "name": "Plage municipale de Roxton Pond",
    "latitude": 45.3833,
    "longitude": -72.4667,
    "description": "Type: Plage | Note: 4.4 (53)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.roxtonpond.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.4
  },
  {
    "id": "spot-0245",
    "name": "Lac Roxton",
    "latitude": 45.3833,
    "longitude": -72.4667,
    "description": "Type: Lac | Note: 4.6 (72)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.roxtonpond.ca/images/lac.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0246",
    "name": "Parc régional de Granby",
    "latitude": 45.4,
    "longitude": -72.7333,
    "description": "Type: Parc régional | Note: 4.8 (623)",
    "address": "Granby, QC",
    "photoURL": "https://www.granby.ca/images/parc.jpg",
    "type": "Parc régional",
    "rating": 4.8
  },
  {
    "id": "spot-0247",
    "name": "Plage municipale de Granby",
    "latitude": 45.4,
    "longitude": -72.7333,
    "description": "Type: Plage | Note: 4.5 (72)",
    "address": "Granby, QC",
    "photoURL": "https://www.granby.ca/images/plage.jpg",
    "type": "Plage",
    "rating": 4.5
  },
  {
    "id": "spot-0248",
    "name": "Lac Boivin",
    "latitude": 45.4,
    "longitude": -72.7333,
    "description": "Type: Lac | Note: 4.6 (84)",
    "address": "Granby, QC",
    "photoURL": "https://www.granby.ca/images/lac-boivin.jpg",
    "type": "Lac",
    "rating": 4.6
  },
  {
    "id": "spot-0249",
    "name": "Parc national de Yamaska",
    "latitude": 45.45,
    "longitude": -72.7333,
    "description": "Type: Parc national | Note: 4.9 (1456)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/yamaska/parc.jpg",
    "type": "Parc national",
    "rating": 4.9
  },
  {
    "id": "spot-0250",
    "name": "Plage de la Yamaska",
    "latitude": 45.45,
    "longitude": -72.7333,
    "description": "Type: Plage | Note: 4.6 (89)",
    "address": "Roxton Pond, QC",
    "photoURL": "https://www.sepaq.com/resources/images/parks/yamaska/plage.jpg",
    "type": "Plage",
    "rating": 4.6
  }
];

export default quebecSpots;
